"""empty message

Revision ID: cee47f3a2572
Revises: 1a9df3919472
Create Date: 2025-07-18 17:41:51.285256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cee47f3a2572'
down_revision = '1a9df3919472'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('birth_year', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('height', sa.String(length=10), nullable=True))

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('climate', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('terrain', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('population', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_column('population')
        batch_op.drop_column('terrain')
        batch_op.drop_column('climate')

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('height')
        batch_op.drop_column('birth_year')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
